name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to Docker hub
      uses: docker/login-action@v1.10.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - uses: actions/checkout@v2
    - name: Build and push
      id: pg10
      uses: docker/build-push-action@v2
      with:
        context: ./10/
        platforms: linux/amd64
        push: true
        tags: philipslabs/postgres-plv8:10
    - name: Build and push
      id: pg11
      uses: docker/build-push-action@v2
      with:
        context: ./11/
        platforms: linux/amd64
        push: true
        tags: philipslabs/postgres-plv8:11
    - name: Build and push
      id: pg12
      uses: docker/build-push-action@v2
      with:
        context: ./12/
        platforms: linux/amd64
        push: true
        tags: philipslabs/postgres-plv8:12
    - name: Build and push
      id: pg13
      uses: docker/build-push-action@v2
      with:
        context: ./13/
        platforms: linux/amd64
        push: true
        tags: philipslabs/postgres-plv8:13
    - name: Build and push
      id: pg14
      uses: docker/build-push-action@v2
      with:
        context: ./14/
        platforms: linux/amd64
        push: true
        tags: philipslabs/postgres-plv8:latest,philipslabs/postgres-plv8:14
    - name: Image digest
      run: |
        echo ${{ steps.pg10.outputs.digest }}
        echo ${{ steps.pg11.outputs.digest }}
        echo ${{ steps.pg12.outputs.digest }}
        echo ${{ steps.pg13.outputs.digest }}
        echo ${{ steps.pg14.outputs.digest }}
